-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC spark.sql("USE CATALOG `lakehouse`")
-- MAGIC spark.sql("USE SCHEMA `default`")

-- COMMAND ----------

-- MAGIC %python
-- MAGIC display(spark.sql("SELECT * FROM samples.wanderbricks.users"))

-- COMMAND ----------

select * from read_files("abfss://raw@adlsnaval123.dfs.core.windows.net/ecom/sales")

-- COMMAND ----------

create schema lakehouse.ayushi_bronze managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/naval_bronze'

-- COMMAND ----------

create schema lakehouse.ayushi_silver managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/naval_silver'

-- COMMAND ----------

create schema lakehouse.ayushi_gold1 managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/naval_gold'
