-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `lakehouse`;
USE SCHEMA `default`;

-- COMMAND ----------

--create schema lakehouse.chetan_silver managed location 'abfss://raw@adlsnaval123.dfs.core.windows.net/lakehouse/chetan_silver'

-- COMMAND ----------


